version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: tandem-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tandem
    ports:
      - "5432:5432"
    volumes:
      - pg-tandem-volume:/var/lib/postgresql/data

  # app:
  #   container_name: tandem-app
  #   build:
  #     context: .
  #     dockerfile: app.dev.dockerfile
  #     target: dev
  #   restart: always
  #   command: pnpm dev
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next
  #   ports:
  #     - 3000:3000

volumes:
  pg-tandem-volume:
